
.global handle_interrupt_0
.align 32
handle_interrupt_0:
push rdi
mov rdi, 0
jmp handle_interrupt_

.global handle_interrupt_1
.align 32
handle_interrupt_1:
push rdi
mov rdi, 1
jmp handle_interrupt_

.global handle_interrupt_2
.align 32
handle_interrupt_2:
push rdi
mov rdi, 2
jmp handle_interrupt_

.global handle_interrupt_3
.align 32
handle_interrupt_3:
push rdi
mov rdi, 3
jmp handle_interrupt_

.global handle_interrupt_4
.align 32
handle_interrupt_4:
push rdi
mov rdi, 4
jmp handle_interrupt_

.global handle_interrupt_5
.align 32
handle_interrupt_5:
push rdi
mov rdi, 5
jmp handle_interrupt_

.global handle_interrupt_6
.align 32
handle_interrupt_6:
push rdi
mov rdi, 6
jmp handle_interrupt_

.global handle_interrupt_7
.align 32
handle_interrupt_7:
push rdi
mov rdi, 7
jmp handle_interrupt_

.global handle_interrupt_8
.align 32
handle_interrupt_8:
push rdi
mov rdi, 8
jmp handle_interrupt_

.global handle_interrupt_9
.align 32
handle_interrupt_9:
push rdi
mov rdi, 9
jmp handle_interrupt_

.global handle_interrupt_10
.align 32
handle_interrupt_10:
push rdi
mov rdi, 10
jmp handle_interrupt_

.global handle_interrupt_11
.align 32
handle_interrupt_11:
push rdi
mov rdi, 11
jmp handle_interrupt_

.global handle_interrupt_12
.align 32
handle_interrupt_12:
push rdi
mov rdi, 12
jmp handle_interrupt_

.global handle_interrupt_13
.align 32
handle_interrupt_13:
push rdi
mov rdi, 13
jmp handle_interrupt_

.global handle_interrupt_14
.align 32
handle_interrupt_14:
push rdi
mov rdi, 14
jmp handle_interrupt_

.global handle_interrupt_15
.align 32
handle_interrupt_15:
push rdi
mov rdi, 15
jmp handle_interrupt_

.global handle_interrupt_16
.align 32
handle_interrupt_16:
push rdi
mov rdi, 16
jmp handle_interrupt_

.global handle_interrupt_17
.align 32
handle_interrupt_17:
push rdi
mov rdi, 17
jmp handle_interrupt_

.global handle_interrupt_18
.align 32
handle_interrupt_18:
push rdi
mov rdi, 18
jmp handle_interrupt_

.global handle_interrupt_19
.align 32
handle_interrupt_19:
push rdi
mov rdi, 19
jmp handle_interrupt_

.global handle_interrupt_20
.align 32
handle_interrupt_20:
push rdi
mov rdi, 20
jmp handle_interrupt_

.global handle_interrupt_21
.align 32
handle_interrupt_21:
push rdi
mov rdi, 21
jmp handle_interrupt_

.global handle_interrupt_22
.align 32
handle_interrupt_22:
push rdi
mov rdi, 22
jmp handle_interrupt_

.global handle_interrupt_23
.align 32
handle_interrupt_23:
push rdi
mov rdi, 23
jmp handle_interrupt_

.global handle_interrupt_24
.align 32
handle_interrupt_24:
push rdi
mov rdi, 24
jmp handle_interrupt_

.global handle_interrupt_25
.align 32
handle_interrupt_25:
push rdi
mov rdi, 25
jmp handle_interrupt_

.global handle_interrupt_26
.align 32
handle_interrupt_26:
push rdi
mov rdi, 26
jmp handle_interrupt_

.global handle_interrupt_27
.align 32
handle_interrupt_27:
push rdi
mov rdi, 27
jmp handle_interrupt_

.global handle_interrupt_28
.align 32
handle_interrupt_28:
push rdi
mov rdi, 28
jmp handle_interrupt_

.global handle_interrupt_29
.align 32
handle_interrupt_29:
push rdi
mov rdi, 29
jmp handle_interrupt_

.global handle_interrupt_30
.align 32
handle_interrupt_30:
push rdi
mov rdi, 30
jmp handle_interrupt_

.global handle_interrupt_31
.align 32
handle_interrupt_31:
push rdi
mov rdi, 31
jmp handle_interrupt_

.global handle_interrupt_32
.align 32
handle_interrupt_32:
push rdi
mov rdi, 32
jmp handle_interrupt_

.global handle_interrupt_33
.align 32
handle_interrupt_33:
push rdi
mov rdi, 33
jmp handle_interrupt_

.global handle_interrupt_34
.align 32
handle_interrupt_34:
push rdi
mov rdi, 34
jmp handle_interrupt_

.global handle_interrupt_35
.align 32
handle_interrupt_35:
push rdi
mov rdi, 35
jmp handle_interrupt_

.global handle_interrupt_36
.align 32
handle_interrupt_36:
push rdi
mov rdi, 36
jmp handle_interrupt_

.global handle_interrupt_37
.align 32
handle_interrupt_37:
push rdi
mov rdi, 37
jmp handle_interrupt_

.global handle_interrupt_38
.align 32
handle_interrupt_38:
push rdi
mov rdi, 38
jmp handle_interrupt_

.global handle_interrupt_39
.align 32
handle_interrupt_39:
push rdi
mov rdi, 39
jmp handle_interrupt_

.global handle_interrupt_40
.align 32
handle_interrupt_40:
push rdi
mov rdi, 40
jmp handle_interrupt_

.global handle_interrupt_41
.align 32
handle_interrupt_41:
push rdi
mov rdi, 41
jmp handle_interrupt_

.global handle_interrupt_42
.align 32
handle_interrupt_42:
push rdi
mov rdi, 42
jmp handle_interrupt_

.global handle_interrupt_43
.align 32
handle_interrupt_43:
push rdi
mov rdi, 43
jmp handle_interrupt_

.global handle_interrupt_44
.align 32
handle_interrupt_44:
push rdi
mov rdi, 44
jmp handle_interrupt_

.global handle_interrupt_45
.align 32
handle_interrupt_45:
push rdi
mov rdi, 45
jmp handle_interrupt_

.global handle_interrupt_46
.align 32
handle_interrupt_46:
push rdi
mov rdi, 46
jmp handle_interrupt_

.global handle_interrupt_47
.align 32
handle_interrupt_47:
push rdi
mov rdi, 47
jmp handle_interrupt_

.global handle_interrupt_48
.align 32
handle_interrupt_48:
push rdi
mov rdi, 48
jmp handle_interrupt_

.global handle_interrupt_49
.align 32
handle_interrupt_49:
push rdi
mov rdi, 49
jmp handle_interrupt_

.global handle_interrupt_50
.align 32
handle_interrupt_50:
push rdi
mov rdi, 50
jmp handle_interrupt_

.global handle_interrupt_51
.align 32
handle_interrupt_51:
push rdi
mov rdi, 51
jmp handle_interrupt_

.global handle_interrupt_52
.align 32
handle_interrupt_52:
push rdi
mov rdi, 52
jmp handle_interrupt_

.global handle_interrupt_53
.align 32
handle_interrupt_53:
push rdi
mov rdi, 53
jmp handle_interrupt_

.global handle_interrupt_54
.align 32
handle_interrupt_54:
push rdi
mov rdi, 54
jmp handle_interrupt_

.global handle_interrupt_55
.align 32
handle_interrupt_55:
push rdi
mov rdi, 55
jmp handle_interrupt_

.global handle_interrupt_56
.align 32
handle_interrupt_56:
push rdi
mov rdi, 56
jmp handle_interrupt_

.global handle_interrupt_57
.align 32
handle_interrupt_57:
push rdi
mov rdi, 57
jmp handle_interrupt_

.global handle_interrupt_58
.align 32
handle_interrupt_58:
push rdi
mov rdi, 58
jmp handle_interrupt_

.global handle_interrupt_59
.align 32
handle_interrupt_59:
push rdi
mov rdi, 59
jmp handle_interrupt_

.global handle_interrupt_60
.align 32
handle_interrupt_60:
push rdi
mov rdi, 60
jmp handle_interrupt_

.global handle_interrupt_61
.align 32
handle_interrupt_61:
push rdi
mov rdi, 61
jmp handle_interrupt_

.global handle_interrupt_62
.align 32
handle_interrupt_62:
push rdi
mov rdi, 62
jmp handle_interrupt_

.global handle_interrupt_63
.align 32
handle_interrupt_63:
push rdi
mov rdi, 63
jmp handle_interrupt_

.global handle_interrupt_64
.align 32
handle_interrupt_64:
push rdi
mov rdi, 64
jmp handle_interrupt_

.global handle_interrupt_65
.align 32
handle_interrupt_65:
push rdi
mov rdi, 65
jmp handle_interrupt_

.global handle_interrupt_66
.align 32
handle_interrupt_66:
push rdi
mov rdi, 66
jmp handle_interrupt_

.global handle_interrupt_67
.align 32
handle_interrupt_67:
push rdi
mov rdi, 67
jmp handle_interrupt_

.global handle_interrupt_68
.align 32
handle_interrupt_68:
push rdi
mov rdi, 68
jmp handle_interrupt_

.global handle_interrupt_69
.align 32
handle_interrupt_69:
push rdi
mov rdi, 69
jmp handle_interrupt_

.global handle_interrupt_70
.align 32
handle_interrupt_70:
push rdi
mov rdi, 70
jmp handle_interrupt_

.global handle_interrupt_71
.align 32
handle_interrupt_71:
push rdi
mov rdi, 71
jmp handle_interrupt_

.global handle_interrupt_72
.align 32
handle_interrupt_72:
push rdi
mov rdi, 72
jmp handle_interrupt_

.global handle_interrupt_73
.align 32
handle_interrupt_73:
push rdi
mov rdi, 73
jmp handle_interrupt_

.global handle_interrupt_74
.align 32
handle_interrupt_74:
push rdi
mov rdi, 74
jmp handle_interrupt_

.global handle_interrupt_75
.align 32
handle_interrupt_75:
push rdi
mov rdi, 75
jmp handle_interrupt_

.global handle_interrupt_76
.align 32
handle_interrupt_76:
push rdi
mov rdi, 76
jmp handle_interrupt_

.global handle_interrupt_77
.align 32
handle_interrupt_77:
push rdi
mov rdi, 77
jmp handle_interrupt_

.global handle_interrupt_78
.align 32
handle_interrupt_78:
push rdi
mov rdi, 78
jmp handle_interrupt_

.global handle_interrupt_79
.align 32
handle_interrupt_79:
push rdi
mov rdi, 79
jmp handle_interrupt_

.global handle_interrupt_80
.align 32
handle_interrupt_80:
push rdi
mov rdi, 80
jmp handle_interrupt_

.global handle_interrupt_81
.align 32
handle_interrupt_81:
push rdi
mov rdi, 81
jmp handle_interrupt_

.global handle_interrupt_82
.align 32
handle_interrupt_82:
push rdi
mov rdi, 82
jmp handle_interrupt_

.global handle_interrupt_83
.align 32
handle_interrupt_83:
push rdi
mov rdi, 83
jmp handle_interrupt_

.global handle_interrupt_84
.align 32
handle_interrupt_84:
push rdi
mov rdi, 84
jmp handle_interrupt_

.global handle_interrupt_85
.align 32
handle_interrupt_85:
push rdi
mov rdi, 85
jmp handle_interrupt_

.global handle_interrupt_86
.align 32
handle_interrupt_86:
push rdi
mov rdi, 86
jmp handle_interrupt_

.global handle_interrupt_87
.align 32
handle_interrupt_87:
push rdi
mov rdi, 87
jmp handle_interrupt_

.global handle_interrupt_88
.align 32
handle_interrupt_88:
push rdi
mov rdi, 88
jmp handle_interrupt_

.global handle_interrupt_89
.align 32
handle_interrupt_89:
push rdi
mov rdi, 89
jmp handle_interrupt_

.global handle_interrupt_90
.align 32
handle_interrupt_90:
push rdi
mov rdi, 90
jmp handle_interrupt_

.global handle_interrupt_91
.align 32
handle_interrupt_91:
push rdi
mov rdi, 91
jmp handle_interrupt_

.global handle_interrupt_92
.align 32
handle_interrupt_92:
push rdi
mov rdi, 92
jmp handle_interrupt_

.global handle_interrupt_93
.align 32
handle_interrupt_93:
push rdi
mov rdi, 93
jmp handle_interrupt_

.global handle_interrupt_94
.align 32
handle_interrupt_94:
push rdi
mov rdi, 94
jmp handle_interrupt_

.global handle_interrupt_95
.align 32
handle_interrupt_95:
push rdi
mov rdi, 95
jmp handle_interrupt_

.global handle_interrupt_96
.align 32
handle_interrupt_96:
push rdi
mov rdi, 96
jmp handle_interrupt_

.global handle_interrupt_97
.align 32
handle_interrupt_97:
push rdi
mov rdi, 97
jmp handle_interrupt_

.global handle_interrupt_98
.align 32
handle_interrupt_98:
push rdi
mov rdi, 98
jmp handle_interrupt_

.global handle_interrupt_99
.align 32
handle_interrupt_99:
push rdi
mov rdi, 99
jmp handle_interrupt_

.global handle_interrupt_100
.align 32
handle_interrupt_100:
push rdi
mov rdi, 100
jmp handle_interrupt_

.global handle_interrupt_101
.align 32
handle_interrupt_101:
push rdi
mov rdi, 101
jmp handle_interrupt_

.global handle_interrupt_102
.align 32
handle_interrupt_102:
push rdi
mov rdi, 102
jmp handle_interrupt_

.global handle_interrupt_103
.align 32
handle_interrupt_103:
push rdi
mov rdi, 103
jmp handle_interrupt_

.global handle_interrupt_104
.align 32
handle_interrupt_104:
push rdi
mov rdi, 104
jmp handle_interrupt_

.global handle_interrupt_105
.align 32
handle_interrupt_105:
push rdi
mov rdi, 105
jmp handle_interrupt_

.global handle_interrupt_106
.align 32
handle_interrupt_106:
push rdi
mov rdi, 106
jmp handle_interrupt_

.global handle_interrupt_107
.align 32
handle_interrupt_107:
push rdi
mov rdi, 107
jmp handle_interrupt_

.global handle_interrupt_108
.align 32
handle_interrupt_108:
push rdi
mov rdi, 108
jmp handle_interrupt_

.global handle_interrupt_109
.align 32
handle_interrupt_109:
push rdi
mov rdi, 109
jmp handle_interrupt_

.global handle_interrupt_110
.align 32
handle_interrupt_110:
push rdi
mov rdi, 110
jmp handle_interrupt_

.global handle_interrupt_111
.align 32
handle_interrupt_111:
push rdi
mov rdi, 111
jmp handle_interrupt_

.global handle_interrupt_112
.align 32
handle_interrupt_112:
push rdi
mov rdi, 112
jmp handle_interrupt_

.global handle_interrupt_113
.align 32
handle_interrupt_113:
push rdi
mov rdi, 113
jmp handle_interrupt_

.global handle_interrupt_114
.align 32
handle_interrupt_114:
push rdi
mov rdi, 114
jmp handle_interrupt_

.global handle_interrupt_115
.align 32
handle_interrupt_115:
push rdi
mov rdi, 115
jmp handle_interrupt_

.global handle_interrupt_116
.align 32
handle_interrupt_116:
push rdi
mov rdi, 116
jmp handle_interrupt_

.global handle_interrupt_117
.align 32
handle_interrupt_117:
push rdi
mov rdi, 117
jmp handle_interrupt_

.global handle_interrupt_118
.align 32
handle_interrupt_118:
push rdi
mov rdi, 118
jmp handle_interrupt_

.global handle_interrupt_119
.align 32
handle_interrupt_119:
push rdi
mov rdi, 119
jmp handle_interrupt_

.global handle_interrupt_120
.align 32
handle_interrupt_120:
push rdi
mov rdi, 120
jmp handle_interrupt_

.global handle_interrupt_121
.align 32
handle_interrupt_121:
push rdi
mov rdi, 121
jmp handle_interrupt_

.global handle_interrupt_122
.align 32
handle_interrupt_122:
push rdi
mov rdi, 122
jmp handle_interrupt_

.global handle_interrupt_123
.align 32
handle_interrupt_123:
push rdi
mov rdi, 123
jmp handle_interrupt_

.global handle_interrupt_124
.align 32
handle_interrupt_124:
push rdi
mov rdi, 124
jmp handle_interrupt_

.global handle_interrupt_125
.align 32
handle_interrupt_125:
push rdi
mov rdi, 125
jmp handle_interrupt_

.global handle_interrupt_126
.align 32
handle_interrupt_126:
push rdi
mov rdi, 126
jmp handle_interrupt_

.global handle_interrupt_127
.align 32
handle_interrupt_127:
push rdi
mov rdi, 127
jmp handle_interrupt_

.global handle_interrupt_128
.align 32
handle_interrupt_128:
push rdi
mov rdi, 128
jmp handle_interrupt_

.global handle_interrupt_129
.align 32
handle_interrupt_129:
push rdi
mov rdi, 129
jmp handle_interrupt_

.global handle_interrupt_130
.align 32
handle_interrupt_130:
push rdi
mov rdi, 130
jmp handle_interrupt_

.global handle_interrupt_131
.align 32
handle_interrupt_131:
push rdi
mov rdi, 131
jmp handle_interrupt_

.global handle_interrupt_132
.align 32
handle_interrupt_132:
push rdi
mov rdi, 132
jmp handle_interrupt_

.global handle_interrupt_133
.align 32
handle_interrupt_133:
push rdi
mov rdi, 133
jmp handle_interrupt_

.global handle_interrupt_134
.align 32
handle_interrupt_134:
push rdi
mov rdi, 134
jmp handle_interrupt_

.global handle_interrupt_135
.align 32
handle_interrupt_135:
push rdi
mov rdi, 135
jmp handle_interrupt_

.global handle_interrupt_136
.align 32
handle_interrupt_136:
push rdi
mov rdi, 136
jmp handle_interrupt_

.global handle_interrupt_137
.align 32
handle_interrupt_137:
push rdi
mov rdi, 137
jmp handle_interrupt_

.global handle_interrupt_138
.align 32
handle_interrupt_138:
push rdi
mov rdi, 138
jmp handle_interrupt_

.global handle_interrupt_139
.align 32
handle_interrupt_139:
push rdi
mov rdi, 139
jmp handle_interrupt_

.global handle_interrupt_140
.align 32
handle_interrupt_140:
push rdi
mov rdi, 140
jmp handle_interrupt_

.global handle_interrupt_141
.align 32
handle_interrupt_141:
push rdi
mov rdi, 141
jmp handle_interrupt_

.global handle_interrupt_142
.align 32
handle_interrupt_142:
push rdi
mov rdi, 142
jmp handle_interrupt_

.global handle_interrupt_143
.align 32
handle_interrupt_143:
push rdi
mov rdi, 143
jmp handle_interrupt_

.global handle_interrupt_144
.align 32
handle_interrupt_144:
push rdi
mov rdi, 144
jmp handle_interrupt_

.global handle_interrupt_145
.align 32
handle_interrupt_145:
push rdi
mov rdi, 145
jmp handle_interrupt_

.global handle_interrupt_146
.align 32
handle_interrupt_146:
push rdi
mov rdi, 146
jmp handle_interrupt_

.global handle_interrupt_147
.align 32
handle_interrupt_147:
push rdi
mov rdi, 147
jmp handle_interrupt_

.global handle_interrupt_148
.align 32
handle_interrupt_148:
push rdi
mov rdi, 148
jmp handle_interrupt_

.global handle_interrupt_149
.align 32
handle_interrupt_149:
push rdi
mov rdi, 149
jmp handle_interrupt_

.global handle_interrupt_150
.align 32
handle_interrupt_150:
push rdi
mov rdi, 150
jmp handle_interrupt_

.global handle_interrupt_151
.align 32
handle_interrupt_151:
push rdi
mov rdi, 151
jmp handle_interrupt_

.global handle_interrupt_152
.align 32
handle_interrupt_152:
push rdi
mov rdi, 152
jmp handle_interrupt_

.global handle_interrupt_153
.align 32
handle_interrupt_153:
push rdi
mov rdi, 153
jmp handle_interrupt_

.global handle_interrupt_154
.align 32
handle_interrupt_154:
push rdi
mov rdi, 154
jmp handle_interrupt_

.global handle_interrupt_155
.align 32
handle_interrupt_155:
push rdi
mov rdi, 155
jmp handle_interrupt_

.global handle_interrupt_156
.align 32
handle_interrupt_156:
push rdi
mov rdi, 156
jmp handle_interrupt_

.global handle_interrupt_157
.align 32
handle_interrupt_157:
push rdi
mov rdi, 157
jmp handle_interrupt_

.global handle_interrupt_158
.align 32
handle_interrupt_158:
push rdi
mov rdi, 158
jmp handle_interrupt_

.global handle_interrupt_159
.align 32
handle_interrupt_159:
push rdi
mov rdi, 159
jmp handle_interrupt_

.global handle_interrupt_160
.align 32
handle_interrupt_160:
push rdi
mov rdi, 160
jmp handle_interrupt_

.global handle_interrupt_161
.align 32
handle_interrupt_161:
push rdi
mov rdi, 161
jmp handle_interrupt_

.global handle_interrupt_162
.align 32
handle_interrupt_162:
push rdi
mov rdi, 162
jmp handle_interrupt_

.global handle_interrupt_163
.align 32
handle_interrupt_163:
push rdi
mov rdi, 163
jmp handle_interrupt_

.global handle_interrupt_164
.align 32
handle_interrupt_164:
push rdi
mov rdi, 164
jmp handle_interrupt_

.global handle_interrupt_165
.align 32
handle_interrupt_165:
push rdi
mov rdi, 165
jmp handle_interrupt_

.global handle_interrupt_166
.align 32
handle_interrupt_166:
push rdi
mov rdi, 166
jmp handle_interrupt_

.global handle_interrupt_167
.align 32
handle_interrupt_167:
push rdi
mov rdi, 167
jmp handle_interrupt_

.global handle_interrupt_168
.align 32
handle_interrupt_168:
push rdi
mov rdi, 168
jmp handle_interrupt_

.global handle_interrupt_169
.align 32
handle_interrupt_169:
push rdi
mov rdi, 169
jmp handle_interrupt_

.global handle_interrupt_170
.align 32
handle_interrupt_170:
push rdi
mov rdi, 170
jmp handle_interrupt_

.global handle_interrupt_171
.align 32
handle_interrupt_171:
push rdi
mov rdi, 171
jmp handle_interrupt_

.global handle_interrupt_172
.align 32
handle_interrupt_172:
push rdi
mov rdi, 172
jmp handle_interrupt_

.global handle_interrupt_173
.align 32
handle_interrupt_173:
push rdi
mov rdi, 173
jmp handle_interrupt_

.global handle_interrupt_174
.align 32
handle_interrupt_174:
push rdi
mov rdi, 174
jmp handle_interrupt_

.global handle_interrupt_175
.align 32
handle_interrupt_175:
push rdi
mov rdi, 175
jmp handle_interrupt_

.global handle_interrupt_176
.align 32
handle_interrupt_176:
push rdi
mov rdi, 176
jmp handle_interrupt_

.global handle_interrupt_177
.align 32
handle_interrupt_177:
push rdi
mov rdi, 177
jmp handle_interrupt_

.global handle_interrupt_178
.align 32
handle_interrupt_178:
push rdi
mov rdi, 178
jmp handle_interrupt_

.global handle_interrupt_179
.align 32
handle_interrupt_179:
push rdi
mov rdi, 179
jmp handle_interrupt_

.global handle_interrupt_180
.align 32
handle_interrupt_180:
push rdi
mov rdi, 180
jmp handle_interrupt_

.global handle_interrupt_181
.align 32
handle_interrupt_181:
push rdi
mov rdi, 181
jmp handle_interrupt_

.global handle_interrupt_182
.align 32
handle_interrupt_182:
push rdi
mov rdi, 182
jmp handle_interrupt_

.global handle_interrupt_183
.align 32
handle_interrupt_183:
push rdi
mov rdi, 183
jmp handle_interrupt_

.global handle_interrupt_184
.align 32
handle_interrupt_184:
push rdi
mov rdi, 184
jmp handle_interrupt_

.global handle_interrupt_185
.align 32
handle_interrupt_185:
push rdi
mov rdi, 185
jmp handle_interrupt_

.global handle_interrupt_186
.align 32
handle_interrupt_186:
push rdi
mov rdi, 186
jmp handle_interrupt_

.global handle_interrupt_187
.align 32
handle_interrupt_187:
push rdi
mov rdi, 187
jmp handle_interrupt_

.global handle_interrupt_188
.align 32
handle_interrupt_188:
push rdi
mov rdi, 188
jmp handle_interrupt_

.global handle_interrupt_189
.align 32
handle_interrupt_189:
push rdi
mov rdi, 189
jmp handle_interrupt_

.global handle_interrupt_190
.align 32
handle_interrupt_190:
push rdi
mov rdi, 190
jmp handle_interrupt_

.global handle_interrupt_191
.align 32
handle_interrupt_191:
push rdi
mov rdi, 191
jmp handle_interrupt_

.global handle_interrupt_192
.align 32
handle_interrupt_192:
push rdi
mov rdi, 192
jmp handle_interrupt_

.global handle_interrupt_193
.align 32
handle_interrupt_193:
push rdi
mov rdi, 193
jmp handle_interrupt_

.global handle_interrupt_194
.align 32
handle_interrupt_194:
push rdi
mov rdi, 194
jmp handle_interrupt_

.global handle_interrupt_195
.align 32
handle_interrupt_195:
push rdi
mov rdi, 195
jmp handle_interrupt_

.global handle_interrupt_196
.align 32
handle_interrupt_196:
push rdi
mov rdi, 196
jmp handle_interrupt_

.global handle_interrupt_197
.align 32
handle_interrupt_197:
push rdi
mov rdi, 197
jmp handle_interrupt_

.global handle_interrupt_198
.align 32
handle_interrupt_198:
push rdi
mov rdi, 198
jmp handle_interrupt_

.global handle_interrupt_199
.align 32
handle_interrupt_199:
push rdi
mov rdi, 199
jmp handle_interrupt_

.global handle_interrupt_200
.align 32
handle_interrupt_200:
push rdi
mov rdi, 200
jmp handle_interrupt_

.global handle_interrupt_201
.align 32
handle_interrupt_201:
push rdi
mov rdi, 201
jmp handle_interrupt_

.global handle_interrupt_202
.align 32
handle_interrupt_202:
push rdi
mov rdi, 202
jmp handle_interrupt_

.global handle_interrupt_203
.align 32
handle_interrupt_203:
push rdi
mov rdi, 203
jmp handle_interrupt_

.global handle_interrupt_204
.align 32
handle_interrupt_204:
push rdi
mov rdi, 204
jmp handle_interrupt_

.global handle_interrupt_205
.align 32
handle_interrupt_205:
push rdi
mov rdi, 205
jmp handle_interrupt_

.global handle_interrupt_206
.align 32
handle_interrupt_206:
push rdi
mov rdi, 206
jmp handle_interrupt_

.global handle_interrupt_207
.align 32
handle_interrupt_207:
push rdi
mov rdi, 207
jmp handle_interrupt_

.global handle_interrupt_208
.align 32
handle_interrupt_208:
push rdi
mov rdi, 208
jmp handle_interrupt_

.global handle_interrupt_209
.align 32
handle_interrupt_209:
push rdi
mov rdi, 209
jmp handle_interrupt_

.global handle_interrupt_210
.align 32
handle_interrupt_210:
push rdi
mov rdi, 210
jmp handle_interrupt_

.global handle_interrupt_211
.align 32
handle_interrupt_211:
push rdi
mov rdi, 211
jmp handle_interrupt_

.global handle_interrupt_212
.align 32
handle_interrupt_212:
push rdi
mov rdi, 212
jmp handle_interrupt_

.global handle_interrupt_213
.align 32
handle_interrupt_213:
push rdi
mov rdi, 213
jmp handle_interrupt_

.global handle_interrupt_214
.align 32
handle_interrupt_214:
push rdi
mov rdi, 214
jmp handle_interrupt_

.global handle_interrupt_215
.align 32
handle_interrupt_215:
push rdi
mov rdi, 215
jmp handle_interrupt_

.global handle_interrupt_216
.align 32
handle_interrupt_216:
push rdi
mov rdi, 216
jmp handle_interrupt_

.global handle_interrupt_217
.align 32
handle_interrupt_217:
push rdi
mov rdi, 217
jmp handle_interrupt_

.global handle_interrupt_218
.align 32
handle_interrupt_218:
push rdi
mov rdi, 218
jmp handle_interrupt_

.global handle_interrupt_219
.align 32
handle_interrupt_219:
push rdi
mov rdi, 219
jmp handle_interrupt_

.global handle_interrupt_220
.align 32
handle_interrupt_220:
push rdi
mov rdi, 220
jmp handle_interrupt_

.global handle_interrupt_221
.align 32
handle_interrupt_221:
push rdi
mov rdi, 221
jmp handle_interrupt_

.global handle_interrupt_222
.align 32
handle_interrupt_222:
push rdi
mov rdi, 222
jmp handle_interrupt_

.global handle_interrupt_223
.align 32
handle_interrupt_223:
push rdi
mov rdi, 223
jmp handle_interrupt_

.global handle_interrupt_224
.align 32
handle_interrupt_224:
push rdi
mov rdi, 224
jmp handle_interrupt_

.global handle_interrupt_225
.align 32
handle_interrupt_225:
push rdi
mov rdi, 225
jmp handle_interrupt_

.global handle_interrupt_226
.align 32
handle_interrupt_226:
push rdi
mov rdi, 226
jmp handle_interrupt_

.global handle_interrupt_227
.align 32
handle_interrupt_227:
push rdi
mov rdi, 227
jmp handle_interrupt_

.global handle_interrupt_228
.align 32
handle_interrupt_228:
push rdi
mov rdi, 228
jmp handle_interrupt_

.global handle_interrupt_229
.align 32
handle_interrupt_229:
push rdi
mov rdi, 229
jmp handle_interrupt_

.global handle_interrupt_230
.align 32
handle_interrupt_230:
push rdi
mov rdi, 230
jmp handle_interrupt_

.global handle_interrupt_231
.align 32
handle_interrupt_231:
push rdi
mov rdi, 231
jmp handle_interrupt_

.global handle_interrupt_232
.align 32
handle_interrupt_232:
push rdi
mov rdi, 232
jmp handle_interrupt_

.global handle_interrupt_233
.align 32
handle_interrupt_233:
push rdi
mov rdi, 233
jmp handle_interrupt_

.global handle_interrupt_234
.align 32
handle_interrupt_234:
push rdi
mov rdi, 234
jmp handle_interrupt_

.global handle_interrupt_235
.align 32
handle_interrupt_235:
push rdi
mov rdi, 235
jmp handle_interrupt_

.global handle_interrupt_236
.align 32
handle_interrupt_236:
push rdi
mov rdi, 236
jmp handle_interrupt_

.global handle_interrupt_237
.align 32
handle_interrupt_237:
push rdi
mov rdi, 237
jmp handle_interrupt_

.global handle_interrupt_238
.align 32
handle_interrupt_238:
push rdi
mov rdi, 238
jmp handle_interrupt_

.global handle_interrupt_239
.align 32
handle_interrupt_239:
push rdi
mov rdi, 239
jmp handle_interrupt_

.global handle_interrupt_240
.align 32
handle_interrupt_240:
push rdi
mov rdi, 240
jmp handle_interrupt_

.global handle_interrupt_241
.align 32
handle_interrupt_241:
push rdi
mov rdi, 241
jmp handle_interrupt_

.global handle_interrupt_242
.align 32
handle_interrupt_242:
push rdi
mov rdi, 242
jmp handle_interrupt_

.global handle_interrupt_243
.align 32
handle_interrupt_243:
push rdi
mov rdi, 243
jmp handle_interrupt_

.global handle_interrupt_244
.align 32
handle_interrupt_244:
push rdi
mov rdi, 244
jmp handle_interrupt_

.global handle_interrupt_245
.align 32
handle_interrupt_245:
push rdi
mov rdi, 245
jmp handle_interrupt_

.global handle_interrupt_246
.align 32
handle_interrupt_246:
push rdi
mov rdi, 246
jmp handle_interrupt_

.global handle_interrupt_247
.align 32
handle_interrupt_247:
push rdi
mov rdi, 247
jmp handle_interrupt_

.global handle_interrupt_248
.align 32
handle_interrupt_248:
push rdi
mov rdi, 248
jmp handle_interrupt_

.global handle_interrupt_249
.align 32
handle_interrupt_249:
push rdi
mov rdi, 249
jmp handle_interrupt_

.global handle_interrupt_250
.align 32
handle_interrupt_250:
push rdi
mov rdi, 250
jmp handle_interrupt_

.global handle_interrupt_251
.align 32
handle_interrupt_251:
push rdi
mov rdi, 251
jmp handle_interrupt_

.global handle_interrupt_252
.align 32
handle_interrupt_252:
push rdi
mov rdi, 252
jmp handle_interrupt_

.global handle_interrupt_253
.align 32
handle_interrupt_253:
push rdi
mov rdi, 253
jmp handle_interrupt_

.global handle_interrupt_254
.align 32
handle_interrupt_254:
push rdi
mov rdi, 254
jmp handle_interrupt_

.global handle_interrupt_255
.align 32
handle_interrupt_255:
push rdi
mov rdi, 255
jmp handle_interrupt_
